# Generated by Django 4.1.7 on 2023-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cid',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
